import { afterEach, describe, expect, it, vi } from "vitest";
import {
  inspectImageBytes,
  loadImage,
  MAX_FILE_BYTES,
  normalizeBox,
  renderCanvas,
  stripPngMetadata,
  type Watermark,
} from "./image";

// Real 3 × 2 images generated by Pillow, including baseline and progressive JPEG.
// Mutated dimension fixtures have valid PNG CRCs but deliberately oversized headers.
const fixtures = {
  png: "iVBORw0KGgoAAAANSUhEUgAAAAMAAAACCAIAAAASFvFNAAAAFElEQVR4nGNUcEhgAAMmCMXAwAAADXwAxIci8GwAAAAASUVORK5CYII=",
  jpeg: "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAACAAMDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDzmiiivTPOP//Z",
  progressive:
    "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wgARCAACAAMDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAUAQEAAAAAAAAAAAAAAAAAAAAE/9oADAMBAAIQAxAAAAGcCTf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAEFAn//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAEDAQE/AX//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAECAQE/AX//xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAY/An//xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAE/IX//2gAMAwEAAgADAAAAEA//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAEDAQE/EH//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAECAQE/EH//xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAE/EH//2Q==",
  metadata:
    "iVBORw0KGgoAAAANSUhEUgAAAAMAAAACCAIAAAASFvFNAAAAFXRFWHRBdXRob3IAUFJJVkFURSBBVVRIT1JAfpoxAAAAH3pUWHRDb21tZW50AAB4nAsI8gxzDHFViPIMCHB1AQAewwQIyFhzqwAAAB1pVFh0TG9jYXRpb24AAAAAAFBSSVZBVEUgTE9DQVRJT06lP6cUAAAAFHZwQWdQUklWQVRFIENVU1RPTSBDSFVOS4KmqLUAAAAOZVhJZklJKgAIAAAAAAAAAAAAb8pcRwAAABRJREFUeJxjVHBIYAADJgjFwMAAAA18AMSHIvBsAAAAAElFTkSuQmCC",
  apng: "iVBORw0KGgoAAAANSUhEUgAAAAMAAAACCAIAAAASFvFNAAAACGFjVEwAAAACAAAAAPONk3AAAAAaZmNUTAAAAAAAAAADAAAAAgAAAAAAAAAAAAEACgAAP7ZcWAAAABRJREFUeJxjVHBIYAADJgjFwMAAAA18AMSHIvBsAAAAGmZjVEwAAAABAAAAAwAAAAIAAAAAAAAAAAABAAoAAKTFtowAAAAYZmRBVAAAAAJ4nGP8//8/AxgwQSgGBgYANgYDAcbpjIcAAAAASUVORK5CYII=",
  tooWide:
    "iVBORw0KGgoAAAANSUhEUgAALuEAAAACCAIAAAD164jQAAAAFElEQVR4nGNUcEhgAAMmCMXAwAAADXwAxIci8GwAAAAASUVORK5CYII=",
  tooManyPixels:
    "iVBORw0KGgoAAAANSUhEUgAAE4gAABOICAIAAADS+hCcAAAAFElEQVR4nGNUcEhgAAMmCMXAwAAADXwAxIci8GwAAAAASUVORK5CYII=",
  palette:
    "iVBORw0KGgoAAAANSUhEUgAAAAMAAAACAQMAAACnuvRZAAAABlBMVEUgQGAAAADBHhOzAAAAAXRSTlMAQObYZgAAAAxJREFUeJxjYGBgAAAABAAB9hc4VQAAAABJRU5ErkJggg==",
};

const bytes = (fixture: keyof typeof fixtures) =>
  Uint8Array.from(atob(fixtures[fixture]), (c) => c.charCodeAt(0));
const file = (
  fixture: keyof typeof fixtures,
  type = "application/octet-stream",
) => new File([bytes(fixture)], "misleading.svg", { type });
const watermark: Watermark = {
  enabled: false,
  text: "",
  opacity: 0.18,
  color: "#000000",
};

afterEach(() => vi.unstubAllGlobals());

describe("binary image preflight", () => {
  it.each([
    ["png", "png"],
    ["palette", "png"],
    ["metadata", "png"],
    ["jpeg", "jpeg"],
    ["progressive", "jpeg"],
  ] as const)("reads dimensions from a real %s fixture", (fixture, format) => {
    expect(inspectImageBytes(bytes(fixture))).toEqual({
      width: 3,
      height: 2,
      format,
    });
  });

  it("rejects actual APNG before browser decoding", () => {
    expect(() => inspectImageBytes(bytes("apng"))).toThrow("动画 PNG");
  });

  it.each(["tooWide", "tooManyPixels"] as const)(
    "rejects oversized %s headers",
    (fixture) => {
      expect(() => inspectImageBytes(bytes(fixture))).toThrow("2000 万像素");
    },
  );

  it.each([
    '<svg xmlns="http://www.w3.org/2000/svg"></svg>',
    "GIF89a",
    "<html>not an image</html>",
  ])("rejects unsupported input %s", (input) => {
    expect(() => inspectImageBytes(new TextEncoder().encode(input))).toThrow(
      "仅支持静态 PNG 或 JPEG",
    );
  });

  it.each(["png", "jpeg", "progressive"] as const)(
    "rejects truncated %s",
    (fixture) => {
      const input = bytes(fixture);
      for (const end of [0, 7, 16, 33, input.length - 1]) {
        expect(() => inspectImageBytes(input.subarray(0, end))).toThrow();
      }
    },
  );

  it("rejects PNG corruption even when the chunk lengths still match", () => {
    const input = bytes("png");
    input[45] = input[45]! ^ 1;
    expect(() => inspectImageBytes(input)).toThrow("校验失败");
  });

  it("rejects oversized chunk and segment lengths", () => {
    const png = bytes("png");
    png.set([0x7f, 0xff, 0xff, 0xff], 33);
    expect(() => inspectImageBytes(png)).toThrow("区块长度超出文件");
    const jpeg = bytes("jpeg");
    jpeg.set([0xff, 0xff], 4);
    expect(() => inspectImageBytes(jpeg)).toThrow("区段已截断");
  });

  it.each(["png", "jpeg"] as const)(
    "rejects bytes after the %s ending",
    (fixture) => {
      const input = new Uint8Array([...bytes(fixture), 0]);
      expect(() => inspectImageBytes(input)).toThrow("结尾无效");
    },
  );

  it("rejects PNG containing only a valid header and ending", () => {
    const original = bytes("png");
    const input = new Uint8Array([
      ...original.subarray(0, 33),
      ...original.subarray(-12),
    ]);
    expect(() => inspectImageBytes(input)).toThrow("像素数据缺失");
  });
});

describe("loading and bitmap ownership", () => {
  it("uses actual bytes and the browser EXIF orientation, ignoring the filename and MIME", async () => {
    const bitmap = { width: 3, height: 2, close: vi.fn() };
    const decode = vi.fn().mockResolvedValue(bitmap);
    vi.stubGlobal("createImageBitmap", decode);
    const input = file("png", "image/svg+xml");
    const loaded = await loadImage(input);
    expect(loaded).toEqual({
      bitmap,
      width: 3,
      height: 2,
      format: "png",
      size: input.size,
    });
    expect(decode).toHaveBeenCalledWith(input, {
      imageOrientation: "from-image",
    });
    expect(bitmap.close).not.toHaveBeenCalled();
  });

  it("accepts orientation-swapped decoded dimensions", async () => {
    vi.stubGlobal(
      "createImageBitmap",
      vi.fn().mockResolvedValue({ width: 2, height: 3, close: vi.fn() }),
    );
    expect(await loadImage(file("jpeg"))).toMatchObject({
      width: 2,
      height: 3,
      format: "jpeg",
    });
  });

  it("rejects oversized files before reading or decoding", async () => {
    const read = vi.fn();
    const decode = vi.fn();
    vi.stubGlobal("createImageBitmap", decode);
    await expect(
      loadImage({
        size: MAX_FILE_BYTES + 1,
        arrayBuffer: read,
      } as unknown as File),
    ).rejects.toThrow("20 MiB");
    expect(read).not.toHaveBeenCalled();
    expect(decode).not.toHaveBeenCalled();
  });

  it.each(["tooWide", "apng"] as const)(
    "rejects %s before the bitmap allocation",
    async (fixture) => {
      const decode = vi.fn();
      vi.stubGlobal("createImageBitmap", decode);
      await expect(loadImage(file(fixture))).rejects.toThrow();
      expect(decode).not.toHaveBeenCalled();
    },
  );

  it("reports decoding failure in plain language", async () => {
    vi.stubGlobal(
      "createImageBitmap",
      vi.fn().mockRejectedValue(new Error("browser-specific codec details")),
    );
    await expect(loadImage(file("png"))).rejects.toThrow("图片无法解码");
  });

  it.each([
    [12001, 1],
    [3, 3],
    [0, 0],
  ])("closes a rejected %s × %s bitmap", async (width, height) => {
    const bitmap = { width, height, close: vi.fn() };
    vi.stubGlobal("createImageBitmap", vi.fn().mockResolvedValue(bitmap));
    await expect(loadImage(file("png"))).rejects.toThrow();
    expect(bitmap.close).toHaveBeenCalledOnce();
  });
});

describe("pixel-safe box coordinates", () => {
  it("normalizes reversed drags and rounds all edges outward", () => {
    expect(
      normalizeBox({ x: 14.2, y: 9.01 }, { x: 2.9, y: 3.8 }, 100, 100),
    ).toEqual({ x: 2, y: 3, width: 13, height: 7 });
  });

  it("clamps drags beyond all four boundaries", () => {
    expect(
      normalizeBox({ x: -20.2, y: 30.4 }, { x: 50.5, y: -1.2 }, 10, 20),
    ).toEqual({ x: 0, y: 0, width: 10, height: 20 });
  });

  it("keeps integer edges exact and outside selections empty", () => {
    expect(normalizeBox({ x: 2, y: 3 }, { x: 7, y: 8 }, 10, 20)).toEqual({
      x: 2,
      y: 3,
      width: 5,
      height: 5,
    });
    expect(normalizeBox({ x: -8, y: -5 }, { x: -2, y: -1 }, 10, 20)).toEqual({
      x: 0,
      y: 0,
      width: 0,
      height: 0,
    });
  });

  it.each([NaN, Infinity, -Infinity])(
    "rejects nonfinite coordinates: %s",
    (x) => {
      expect(() => normalizeBox({ x, y: 0 }, { x: 1, y: 1 }, 10, 10)).toThrow(
        "有限数字",
      );
    },
  );

  it("rejects invalid crop, opacity, and transparent colors before drawing", () => {
    const source = {} as CanvasImageSource;
    expect(() =>
      renderCanvas(
        source,
        10,
        10,
        [],
        { x: 0.5, y: 0, width: 0, height: 1 },
        watermark,
      ),
    ).toThrow("实际面积");
    expect(() =>
      renderCanvas(
        source,
        10,
        10,
        [],
        { x: NaN, y: 0, width: 1, height: 1 },
        watermark,
      ),
    ).toThrow("尺寸无效");
    expect(() =>
      renderCanvas(source, 10, 10, [], null, { ...watermark, opacity: 1.01 }),
    ).toThrow("水印设置无效");
    expect(() =>
      renderCanvas(source, 10, 10, [], null, {
        ...watermark,
        text: "字".repeat(81),
      }),
    ).toThrow("最多 80");
    expect(() =>
      renderCanvas(
        source,
        10,
        10,
        [{ id: "a", x: 0, y: 0, width: 1, height: 1, color: "#00000080" }],
        null,
        watermark,
      ),
    ).toThrow("不透明");
  });
});

describe("export metadata removal", () => {
  it("removes EXIF, all text forms, and private data while preserving exact pixel chunks", () => {
    const input = bytes("metadata");
    const original = input.slice();
    expect(stripPngMetadata(input)).toEqual(bytes("png"));
    expect(input).toEqual(original);
  });

  it("preserves palettes and transparency needed to decode a PNG", () => {
    expect(stripPngMetadata(bytes("palette"))).toEqual(bytes("palette"));
  });

  it("rejects truncated or animated output instead of passing it through", () => {
    expect(() => stripPngMetadata(bytes("png").subarray(0, 50))).toThrow();
    expect(() => stripPngMetadata(bytes("apng"))).toThrow("动画 PNG");
  });
});
